class ModelEnum:
    LOGISTIC_REGRESSION = "LOGISTIC_REGRESSION"
    KNN = "KNN"
    SVM = "SVM"
    NAIVE_BAYES = "NAIVE_BAYES"
    DECISION_TREE = "DECISION_TREE"
    LINEAL_REGRESSION = "LINEAL_REGRESSION"
